In [1]:
import numpy as np

In [2]:
@np.vectorize
def FtoC(a):
    return (a-32)*5/9
arr = np.array([32, 68, 100, 212, 77])
print(FtoC(arr))

[  0.          20.          37.77777778 100.          25.        ]


In [3]:
@np.vectorize
def power(a,b):
    return a**b
a = np.array([2, 3, 4, 5])
b = np.array([1, 2, 3, 4])
print(power(a,b))

[  2   9  64 625]


In [ ]:
A = np.array([[4, 5, 6], [3, -1, 1], [2, 1, -2]])
B = np.array([7, 4, 5])
print(np.linalg.solve(A, B))

[ 1.7027027   0.62162162 -0.48648649]


In [5]:
I = np.array([[10, -2, -3], [-2, 8, -1], [3, -1, 6]])
C = np.array([12, -5, 15])
print(np.linalg.solve(I,C))

[1.6969112  0.00579151 1.65250965]
