In [1]:
import numpy as np

- Create a vector with values ranging from 10 to 49.
- Create a 3x3 matrix with values ranging from 0 to 8.
- Create a 3x3 identity matrix.
- Create a 3x3x3 array with random values.
- Create a 10x10 array with random values and find the minimum and maximum values.
- Create a random vector of size 30 and find the mean value.
- Normalize a 5x5 random matrix.
- Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
- Create two 3x3 matrices and compute their dot product.
- Given a 4x4 matrix, find its transpose.
- Create a 3x3 matrix and calculate its determinant.
- Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).
- Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
- Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.
- Given a 5x5 matrix, find the row-wise and column-wise sums.

In [63]:
def randomize(*args,type=int):
    return np.array(np.random.random(args)*10,dtype=type)

In [ ]:
rng=np.arange(10,50)
print(rng)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
rng3d=np.reshape(np.arange(9),(3,3))
print(rng3d)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
identity_matrix = np.eye(3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [65]:
rnd3d = randomize(3,3,3)
print(rnd3d)

[[[4 2 4]
  [2 7 5]
  [9 7 6]]

 [[3 8 4]
  [0 9 7]
  [6 0 7]]

 [[1 4 9]
  [6 9 5]
  [3 4 8]]]


In [66]:
rnd10x10 = randomize(10,10)
minn = rnd10x10.min()
maxx = rnd10x10.max()
print(rnd10x10)
print("Minimum Value:", minn)
print("Maximum Value:", maxx)

[[5 4 6 2 0 6 2 4 4 2]
 [1 4 7 0 4 5 1 3 8 5]
 [0 3 2 1 0 3 3 2 1 9]
 [7 4 0 1 2 6 6 3 1 7]
 [8 1 1 3 2 1 1 9 1 7]
 [6 5 4 3 5 5 2 1 9 6]
 [9 3 3 3 5 9 9 5 3 5]
 [6 5 0 5 1 0 0 8 2 5]
 [6 0 7 4 8 6 8 5 6 8]
 [4 3 8 1 5 0 0 1 2 3]]
Minimum Value: 0
Maximum Value: 9


In [68]:
rnd30 = randomize(30)
mean = rnd30.mean()
print(rnd30)
print("Mean Value:", mean)

[2 3 2 9 0 9 7 8 9 6 6 8 5 8 8 9 7 0 2 6 5 7 0 3 1 6 0 2 4 4]
Mean Value: 4.866666666666666


In [71]:
rnd5x5 = randomize(5,5)
normalized_matrix = (rnd5x5 - rnd5x5.mean()) / rnd5x5.std()
print("Original:\n",rnd5x5)
print("Normalized:\n", normalized_matrix)

Original:
 [[1 2 3 1 0]
 [5 7 2 2 9]
 [2 7 2 4 4]
 [9 8 2 3 4]
 [7 3 3 8 0]]
Normalized:
 [[-1.06526784 -0.70045009 -0.33563233 -1.06526784 -1.43008559]
 [ 0.39400317  1.12363868 -0.70045009 -0.70045009  1.85327419]
 [-0.70045009  1.12363868 -0.70045009  0.02918542  0.02918542]
 [ 1.85327419  1.48845643 -0.70045009 -0.33563233  0.02918542]
 [ 1.12363868 -0.33563233 -0.33563233  1.48845643 -1.43008559]]


In [72]:
mtrx5x3 = randomize(5,3)
mtrx3x2 = randomize(3,2)
print("5x3 Matrix:\n", mtrx5x3)
print("3x2 Matrix:\n", mtrx3x2)
print("Matrix Product (5x3 * 3x2):\n", np.dot(mtrx5x3, mtrx3x2))

5x3 Matrix:
 [[6 4 9]
 [4 3 8]
 [3 9 1]
 [2 7 9]
 [7 7 8]]
3x2 Matrix:
 [[7 5]
 [1 0]
 [6 9]]
Matrix Product (5x3 * 3x2):
 [[100 111]
 [ 79  92]
 [ 36  24]
 [ 75  91]
 [104 107]]


In [73]:
a3x3 = randomize(3,3)
b3x3 = randomize(3,3)
print("3x3 Matrix A:\n", a3x3)
print("3x3 Matrix B:\n", b3x3)
print("Dot Product of A and B:\n", np.dot(a3x3, b3x3))

3x3 Matrix A:
 [[3 0 7]
 [1 9 4]
 [6 7 5]]
3x3 Matrix B:
 [[3 2 0]
 [2 0 1]
 [0 9 1]]
Dot Product of A and B:
 [[ 9 69  7]
 [21 38 13]
 [32 57 12]]


In [ ]:
mtrx4x4 = randomize(4,4)
print("4x4 Matrix:\n", mtrx4x4)
print("Transpose of the 4x4 Matrix:\n", mtrx4x4.T)

4x4 Matrix:
 [[2 7 5 5]
 [4 3 3 4]
 [8 2 8 4]
 [7 1 6 3]]
Transpose of the 4x4 Matrix:
 [[2 4 8 7]
 [7 3 2 1]
 [5 3 8 6]
 [5 4 4 3]]


In [76]:
mtrx3x3 = randomize(3,3)
print("3x3 Matrix:\n", mtrx3x3)
print("Determinant of the 3x3 Matrix:", np.linalg.det(mtrx3x3))

3x3 Matrix:
 [[2 2 8]
 [6 5 4]
 [3 5 5]]
Determinant of the 3x3 Matrix: 94.0


In [77]:
mtrxA = randomize(3,4)
mtrxB = randomize(4,3)
print("Matrix A (3x4):\n", mtrxA)
print("Matrix B (4x3):\n", mtrxB)
print("Matrix Product (A · B):\n", np.dot(mtrxA, mtrxB))

Matrix A (3x4):
 [[7 0 7 3]
 [1 6 3 8]
 [0 0 4 0]]
Matrix B (4x3):
 [[5 6 0]
 [8 4 6]
 [1 6 8]
 [5 8 5]]
Matrix Product (A · B):
 [[ 57 108  71]
 [ 96 112 100]
 [  4  24  32]]


In [78]:
mtrx3x3 = randomize(3,3)
vec3 = randomize(3)
print("3x3 Random Matrix:\n", mtrx3x3)
print("3-Element Column Vector:\n", vec3)
print("Matrix-Vector Product:\n", np.dot(mtrx3x3, vec3))

3x3 Random Matrix:
 [[8 4 3]
 [4 3 4]
 [7 8 0]]
3-Element Column Vector:
 [4 5 1]
Matrix-Vector Product:
 [55 35 68]


In [79]:
A = randomize(3,3)
b = randomize(3)
print("Matrix A (3x3):\n", A)
print("Column Vector b (3x1):\n", b)
print("Solution x of the Linear System (Ax = b):\n", np.linalg.solve(A, b))

Matrix A (3x3):
 [[9 4 4]
 [7 3 5]
 [6 8 7]]
Column Vector b (3x1):
 [3 9 5]
Solution x of the Linear System (Ax = b):
 [-0.2 -2.2  3.4]


In [80]:
mtrx5x5 = randomize(5,5)
row_sum = mtrx5x5.sum(axis=1)
col_sum = mtrx5x5.sum(axis=0)
print("5x5 Matrix:\n", mtrx5x5)
print("Row-wise Sums:\n", row_sum)
print("Column-wise Sums:\n", col_sum)

5x5 Matrix:
 [[9 5 4 7 5]
 [7 4 5 8 6]
 [9 8 4 3 6]
 [9 8 0 9 2]
 [1 0 9 0 8]]
Row-wise Sums:
 [30 30 30 28 18]
Column-wise Sums:
 [35 25 22 27 27]
